<?php $month = date('F'); ?>
<header>
    <h2 class="fa fa-2x fa-star"> <?php echo $month; ?> Highscore</h2>
</header>
<table style="width:100%;height:100%;" class="padded-table">
    <tr>
        <td style="width:15%;border-bottom:1px dotted #999;">Rank</td>
        <td style="width:15%;border-bottom:1px dotted #999;">Level</td>
        <td style="width:30%;border-bottom:1px dotted #999;">Score</td>
        <td style="width:40%;border-bottom:1px dotted #999;">User</td>
    </tr>
    <?php
    $rank = $positions['rank'] - $positions['countRowsHighscorePrev'];
    foreach($positions['positions'] as $position){
        ?>
        <tr style="<?php echo $position->user==$_SESSION['user'] ? 'background-color:#009900;color:white;' : ''; ?>">
            <td><?php echo $rank; ?></td>
            <td>
                <?php
                if(($game_id==8 || $game_id==7 || $game_id==6) && $position->level>=11){
                    echo 'Win!';
                } else{
                    echo $position->level;
                }
                ?>
            </td>
            <td><?php echo $position->score; ?></td>
            <td>

                <?php if($position->approved==1){ ?>
                    <a style="color:white" href="/player/<?php echo $position->user; ?>/"><?php echo $position->user; ?></a>
                <?php } else { ?>
                    <?php echo $position->user; ?>
                <?php } ?>

            </td>
        </tr>
        <?php
        $rank++;
    }
    ?>
    <tr>
        <td colspan="4"><br/><a class="button alt small fa fa-magic" href="/scores/<?php echo $game_id; ?>/0/">View Ranks</a></td>
    </tr>
</table>
