<?php include_once($theme."/html/header.phtml");?>
<!-- Main Wrapper -->
<div id="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="4u">

                <!-- Sidebar -->
                <div id="sidebar">
                    <section class="widget-links">
                        <h3>&nbsp;</h3>
                        <div class="grid">
                            <div class="row no-collapse half">
                                <div class="9u"><a class="button small fa fa-gamepad" href="/game/<?php echo $swf_id; ?>/<?php echo $cleanname; ?>/">Play <?php echo $game_name; ?></a></div>
                            </div>
                        </div>
                    </section>

                    <section class="widget-links">
                        <h2 class="fa fa-2x fa-eye"> More scores</h2>
                        <div class="grid">
                            <?php $others = array(10,6,5,7,8,4,3,2,1); ?>
                            <?php for($i=0; $i<count($others); $i++ ){ ?>
                            <div class="row no-collapse half">
                                <div class="9u"><a class="button alt small fa fa-magic" href="/scores/<?php echo $others[$i]; ?>/0/"><?php echo $games[$others[$i]]['title'] ?></a></div>
                            </div>
                            <?php } ?>
                        </div>
                    </section>

                </div>

            </div>
            <div class="8u">

                <!-- Content -->
                <div id="content">
                    <section class="last">

                        <h2 class="fa fa-2x fa-star"> <?php echo $game_name." - ".date('F'); ?> Highscore</h2>
                        <?php if(!$scores){ ?>
                            Sorry no scores yet!
                        <?php } ?>

                        <?php if($scores){ ?>
                            <table width="100%">
                                <tr>
                                    <td style="width:15%;border-bottom:1px dotted #999;">Position</td>
                                    <td style="width:15%;border-bottom:1px dotted #999;">Avatar</td>
                                    <td style="width:20%;border-bottom:1px dotted #999;">Player</td>
                                    <td style="width:10%;border-bottom:1px dotted #999;">Level</td>
                                    <td style="width:20%;border-bottom:1px dotted #999;">Score</td>
                                    <td style="width:20%;border-bottom:1px dotted #999;">&nbsp;</td>
                                </tr>
                                <?php
                                $limit_from += 1;
                                $amountDisplayCount = 0;
                                foreach($scores as $score){
                                    if($amountDisplayCount<$amountDisplay){
                                        $amountDisplayCount++ ;
                                        ?>
                                        <tr>
                                            <td style="border-bottom:1px solid #dddddd;"><?php echo $limit_from++; ?></td>
                                            <td style="border-bottom:1px solid #dddddd;"><?php echo ($score->email!=''&&$score->approved==1) ? '<img src="'.AvatarHelper::imgurl($score->email).'" />' : ''; ?></td>
                                            <td style="border-bottom:1px solid #dddddd;">
                                                <?php if($score->email!=''&&$score->approved==1){ ?>

		<a href="/player/<?php echo $score->user; ?>/"><?php echo $score->user; ?></a>

                                                    <?php echo AvatarHelper::imglevel($score->points); ?>
                                                <?php } else { ?>
                                                    <?php echo $score->user; ?>
                                                <?php } ?>
                                            </td>
                                            <td style="border-bottom:1px solid #dddddd;">
                                                <?php
                                                if(($game_id==8 || $game_id==7 || $game_id==6) && $score->level>=11){
                                                    echo 'Win';
                                                } else{
                                                    echo $score->level;
                                                }
                                                ?>
                                            </td>
                                            <td style="border-bottom:1px solid #dddddd;"><b><?php echo $score->score; ?></b></td>
                                            <td style="border-bottom:1px solid #dddddd;"><span style="color:#bbbbbb;"><?php echo DateFormatHelper::niceShort($score->created); ?></span></td>
                                        </tr>
                                    <?php
                                    }}
                                ?>
                            </table>
                            <table width="100%">
                                <tr>
                                    <td style="width:50px;text-align:left" valign="top">
                                        <?php if($page_no>0){ ?>
                                        <a href="/scores/<?php echo $game_id; ?>/<?php echo ($page_no-1); ?>/" style="text-decoration:underline;">Before</a></td>
                                    <?php } ?>
                                    </td>
                                    <td style="text-align:center;">
                                        <?php
                                        $amountOfPages = $amountOfScores/$amountDisplay;
                                        for($i=0; $i<=$amountOfPages; $i++){
                                            ?>
                                            <a title="<?php echo ($i*$amountDisplay+1)."-".($i*$amountDisplay+$amountDisplay); ?>" href="/scores/<?php echo $game_id; ?>/<?php echo ($i); ?>/" style="text-decoration:underline;">.</a>
                                            <?php
                                            echo ($i%50==0) ? '<br/>' : '';
                                        }
                                        ?>
                                    </td>
                                    <td style="width:50px;text-align:right" valign="top">
                                        <?php if(count($scores)>$amountDisplay){ ?>
                                            <a href="/scores/<?php echo $game_id; ?>/<?php echo ($page_no+1); ?>/" style="text-decoration:underline;">Next</a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            </table>
                        <?php } ?>
                    </section>
                </div>

            </div>
        </div>
    </div>
</div>


<!-- Features Wrapper -->
<div id="features-wrapper">
    <div class="container">
        <div class="row">

            <?php
            if(!$monthlyTopscoresByGameId){
                echo "Sorry no winners yet!";
            }
            $i = 0;
            foreach($monthlyTopscoresByGameId as $key_year => $year){
                foreach($year as $key_month => $month){
                    $last = $i%3==2 ? 'last' : '';
                    ?>
            <div class="4u">
                <section class="box box-feature <?php echo $last; ?>">
                    <div class="inner">
                        <header>
                            <h2 class="fa fa-2x fa-star"> <?php echo DateFormatHelper::month($key_month); ?> <?php echo $key_year; ?></h2>
                        </header>

                        <table class="padded-table" border="0" style="width:100%;height:100%;">
                            <tr>
                                <td width="20%" style="text-align:center;">Rank</td>
                                <td width="20%">Avatar</td>
                                <td width="20%">Player</td>
                                <td width="20%">Level</td>
                                <td width="20%">Score</td>
                            </tr>
                            <?php
                            $rank = 1;
                            foreach($month as $postion=>$player){
                                ?>
                                <tr>
                                    <td style="border-top:1px dotted #999;text-align:center;"><?php echo $rank++; ?></td>
                                    <td style="border-top:1px dotted #999;"><?php echo ($player['email']!=''&&$player['approved']==1) ? '<img style="height:30px;" src="'.AvatarHelper::imgurl($player['email']).'" />' : '<div style="height:30px;"></div>'; ?></td>
                                    <td style="border-top:1px dotted #999;"><?php echo $player['user']; ?></td>
                                    <td style="border-top:1px dotted #999;">
                                        <?php
                                        if(($game_id==8 || $game_id==7 || $game_id==6) && $player['level']>=11){
                                            echo 'Win';
                                        } else{
                                            echo $player['level'];
                                        }
                                        ?>
                                    </td>
                                    <td style="border-top:1px dotted #999;"><b><?php echo $player['score']; ?></b></td>
                                </tr>
                            <?php } ?>
                        </table>
                    </div>
                </section>
                </div>

                    <?php if($i%3==2){ ?>
        </div><div class="row">
                    <?php }
                    $i++;
                    $monthCount++;
                }
                ?>
            <?php
            }
            ?>

        </div>
    </div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
