<?php include_once($theme."/html/header.phtml");?>

<!-- Main Wrapper -->
<div id="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="4u">

                <!-- Sidebar -->
                <div id="sidebar">
                    <section class="widget-links">
                        <h3>Related Options</h3>
                        <div class="grid">
                            <div class="row no-collapse half">
                                <div class="9u"><a class="button" href="/register/">Create Account</a></div>
                            </div>
                            <div class="row no-collapse half">
                                <div class="9u"><a class="button" href="/login/">Sign in</a></div>
                            </div>
                        </div>
                    </section>
                </div>

            </div>
            <div class="8u">

                <!-- Content -->
                <div id="content">
                    <section class="last">

                        <h2>Reset password</h2>

                        <form id="form" method="post">

                            <div class="header">

                                <?php
                                $style=' style="" ';
                                ?>
                                <?php if(count($error)>0){ ?>
                                    <h3>Ooops!</h3>
                                    <?php
                                    if(isset($error)){
                                        $style=' style="background:#ff0000;" ';
                                        ?>
                                        <h2 style="color: #ff0000;"><?php echo $error; ?></h2>
                                    <?php } ?>
                                <?php } ?>

                                <h3>Lost password</h3>
                                <p>
                                    Please tell us your email address! We are going to send you a new password by email.
                                </p>

                            </div>

                            <div class="sep"></div>

                            <div class="inputs">

                                <div>
                                    <input type="email" name="email" <?php echo $style; ?> placeholder="E-Mail" value="<?php echo $email; ?>" />
                                </div>

                                <div>
                                    <input type="hidden" name="nr1" id="nr1" value="<?php echo $nr1; ?>" />
                                    <input type="hidden" name="nr2" id="nr2" value="<?php echo $nr2; ?>" />
                                    <input type="text" name="total" id="total" <?php echo $style; ?> placeholder="<?php echo $nr1; ?> + <?php echo $nr2; ?> =" />
                                    <br/>
                                </div>

                                <div>
                                    <input type="submit" class="button" value="Sign up">
                                </div>

                            </div>

                        </form>

                    </section>
                </div>

            </div>
        </div>
    </div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
