<?php include_once($theme."/html/header.phtml");?>

<!-- Main Wrapper -->
<div id="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="4u">

                <!-- Sidebar -->
                <div id="sidebar">
                    <section class="widget-links">
                        <h3>Related Options</h3>
                        <div class="grid">
                            <div class="row no-collapse half">
                                <div class="9u"><a class="button" href="/lostpassword/">Reset password</a></div>
                            </div>
                            <div class="row no-collapse half">
                                <div class="9u"><a class="button" href="/login/">Sign in</a></div>
                            </div>
                        </div>
                    </section>
                </div>

            </div>
            <div class="8u">

                <!-- Content -->
                <div id="content">
                    <section class="last">
                        <h2>OK</h2>
                        <p>We have sent you an email with a link to activate your account!</p>

                    </section>
                </div>

            </div>
        </div>
    </div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
