<?php include_once($theme."/html/header.phtml");?>

<style type="text/css">
table.padded-table td { padding:5px; }
</style>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">

  <div class="gap">

   <!-- start -->
<div>

<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
        codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0"
        width="800"
        height="600"
        id="game"
        align="middle">
<param name="movie" value="/swf/<?php echo $swf_id; ?>/game.swf" />
<param name="allowScriptAccess" value="sameDomain" />
<param name="allowFullScreen" value="true" />
<param name="menu" value="false" />
<param name="FlashVars" value="player=<?php echo $user; ?>"/>
<param name="quality" value="high" /><param name="bgcolor" value="<?php echo $bgColor; ?>" />
        <embed src="/swf/<?php echo $swf_id; ?>/game.swf"
                        FlashVars="player=<?php echo $user; ?>"
                        quality="high"
                        menu="false"
                        bgcolor="<?php echo $bgColor; ?>"
                        width="800"
                        height="600"
                        allowFullScreen="true"
                        allowFullScreenInteractive="true"
                        name="game"
                        align="middle"
                        allowScriptAccess="sameDomain"
                        type="application/x-shockwave-flash"
                        pluginspage="http://www.macromedia.com/go/getflashplayer" />
</object>
</div>
                                <div class="superflow">
                                        <!--  current leadership -->
                                        <div class="box" style="float:left;width:50%;">
                                                <div style="margin:10px;">
                                                        <h3 style="padding:2px;">Current Leadership</h3>
                                                        <div style="border:1px dotted #666666;background-color:#eeeeee;">
                                                                <table style="width:100%;height:100%;" class="padded-table">
                                                                        <?php if($currentLeadershipByGameId){ ?>
                                                                        <tr>
                                                                                <td style="width:10%;border-bottom:1px dotted #999;">&nbsp;</td>
                                                                                <td style="width:45%;border-bottom:1px dotted #999;">Player</td>
                                                                                <td style="width:35%;border-bottom:1px dotted #999;">Score</td>
                                                                                <td style="width:10%;border-bottom:1px dotted #999;">Level</td>
                                                                        </tr>
                                                                        <?php $i=1; foreach($currentLeadershipByGameId as $leader){ ?>
                                                                        <tr>
                                                                                <td><?php echo $i++; ?></td>
                                                                                <td><a href="/player/<?php echo $leader['user']; ?>/"><?php echo $leader['user']; ?></a></td>
                                                                                <td><?php echo $leader['score']; ?></td>
                                                                                <td>
                                                                                <?php
                                                                                if(($game_id==8 || $game_id==7 || $game_id==6) && $leader['level']>=11){
                                                                                        echo 'Win';
                                                                                } else{
                                                                                        echo $leader['level'];
                                                                                }
                                                                                ?>
                                                                        </tr>
                                                                        <?php } ?>
                                                                        <tr>
                                                                                <td colspan="4">
                                                                                        <!--&rarr; <a href="/scores/<?php echo $game_id; ?>/0/" style="padding-top:5px;text-decoration:underline;">See all</a>-->
                                                                                </td>
                                                                        </tr>
                                                                        <?php } else { ?>
                                                                        <tr>
                                                                                <td valign="top"><p>No Leadership yet!</p></td>
                                                                        </tr>
                                                                        <?php } ?>
                                                                        <tr>
                                                                                <td colspan="4"><a href="/scores/<?php echo $game_id; ?>/0/">→ See this month leadership</a></td>
                                                                        </tr>
                                                                </table>
                                                        </div>
                                                </div>
                                        </div>

                                        <!--  alltime stars -->
                                        <div class="box" style="float:left;width:50%;">
                                                <div style="margin:10px;">
                                                        <h3 style="padding:2px;">Alltime Heros</h3>
                                                        <div style="border:1px dotted #666666;background-color:#eeeeee;">
                                                                <table style="width:100%;height:100%;" class="padded-table">
                                                                        <?php if($allTimeStarsByGameId){ ?>
                                                                        <tr>
                                                                                <td style="width:10%;border-bottom:1px dotted #999;">&nbsp;</td>
                                                                                <td style="width:45%;border-bottom:1px dotted #999;">Player</td>
                                                                                <td style="width:35%;border-bottom:1px dotted #999;">Score</td>
                                                                                <td style="width:10%;border-bottom:1px dotted #999;">Level</td>
                                                                        </tr>
                                                                        <?php $i=1; foreach($allTimeStarsByGameId as $star){ ?>
                                                                        <tr>
                                                                                <td><?php echo $i++; ?></td>
                                                                                <td><a href="/player/<?php echo $star['user']; ?>/"><?php echo $star['user']; ?></a></td>
                                                                                <td><?php echo $star['score']; ?></td>
                                                                                <td>
                                                                                <?php
                                                                                if(($game_id==8 || $game_id==7 || $game_id==6) && $star['level']>=11){
                                                                                        echo 'Win';
                                                                                } else{
                                                                                        echo $star['level'];
                                                                                }
                                                                                ?>
                                                                                </td>
                                                                        </tr>
                                                                        <?php } ?>
                                                                        <tr>
                                                                                <td colspan="4">
                                                                                        <!-- &rarr; <a href="/winners/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/" style="padding-top:5px;text-decoration:underline;">See all</a> -->
                                                                                </td>
                                                                        </tr>
                                                                        <?php } else { ?>
                                                                        <tr>
                                                                                <td valign="top"><p>No heros yet!</p></td>
                                                                        </tr>
                                                                        <?php } ?>
									<tr>
										<td colspan="4"><a href="/winners/<?php echo $game_id; ?>/">→ See all past winners</a></td>
									</tr>
                                                                </table>
                                                        </div>
                                                </div>
                                        </div>
<!--  infobox -->
<!--
                                        <div class="box" style="float:left;width:33%;">
                                                <div style="margin:10px;">
                                                        <h3 style="padding:2px;">Ads</h3>
                                                        <div style="border:1px dotted #666666;background-color:#eeeeee;">
                                                                <table style="width:100%;height:100%;" class="padded-table">
                                                                        <tr>
                                                                                <td valign="top">
                                                                                <?php if($game['coins']==0){ ?>
                                                                                <p>
                                                                                        &rarr; <a href="/play/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/">Play now!</a>
                                                                                </p>
                                                                                <?php } else if($game['coins']>=0) { ?>
                                                                                        <?php if(!isset($_SESSION['accountId'])){ ?>
                                                                                        <p>
                                                                                                This game is not for free and requires an account!
                                                                                                <br/>
                                                                                                &rarr; <a href="/register/">Sign in!</a>
                                                                                                <br/>
                                                                                                &rarr; <a href="/login/?next=/game/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/">Login!</a>
                                                                                        </p>
                                                                                        <?php } else { ?>
                                                                                                <?php if($accountProduct){ ?>
                                                                                                <p>
                                                                                                        This game expires on:
                                                                                                        <br/>
                                                                                                        <?php echo DateFormatHelper::standard($accountProduct->expires); ?>
                                                                                                        <br/>
                                                                                                        &rarr; <a href="/play/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/">Play now!</a>
                                                                                                </p>
                                                                                                <?php } else { ?>
                                                                                                        <?php if($amountCoins<$game['coins']){ ?>
                                                                                                        <p>
                                                                                                                You require <b><?php echo $game['coins']>1 ? $game['coins'].' coins ' : $game['coins']. ' coin'; ?></b> to activate this game.
                                                                                                                <br/>
                                                                                                                &rarr; <a href="/coins/">Buy coins!</a>
                                                                                                        </p>
                                                                                                        <?php } else { ?>
                                                                                                        <p>
                                                                                                                You require <b><?php echo $game['coins']>1 ? $game['coins'].' coins ' : $game['coins']. ' coin'; ?></b> to activate this game for 30 days.
                                                                                                                <br/>
                                                                                                                &rarr; <a href="/buy/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/?next=/play/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/">Activate this game!</a>
                                                                                                        </p>
                                                                                                        <?php } ?>
                                                                                                <?php } ?>
                                                                                        <?php } ?>
                                                                                <?php } ?>
                                                                                </td>
                                                                        </tr>
                                                                </table>
                                                        </div>
                                                </div>
                                        </div>
-->
                                </div>
                        </div> <!-- /gap -->
                </div> <!-- /content -->
        </div> <!-- /content-wrap -->

<?php include_once($theme."/html/games/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
