<?php include_once($theme."/html/header.phtml");?>
<!-- Main Wrapper -->
<div id="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="8u">

                <!-- Content -->
                <div id="content">
                    <section class="last">
                        <header>
                            <h2 class="fa fa-2x fa-area-chart"> New accounts</h2>
                            <p>Amount of all and approved new accounts of the last 12 month</p>
                        </header>
                        <div class="grid">
                            <canvas id="canvasNewAccounts" height="240" width="760"></canvas>
                            <script>
                                var data = {labels:[]};
                                data.datasets = [{
                                    label: "All new accounts",
                                    fillColor: "rgba(220,220,220,0.2)",
                                    strokeColor: "rgba(220,220,220,1)",
                                    pointColor: "rgba(220,220,220,1)",
                                    pointStrokeColor: "#fff",
                                    pointHighlightFill: "#fff",
                                    pointHighlightStroke: "rgba(220,220,220,1)",
                                    data:[]
                                },{
                                    label: "Approved new accounts",
                                    fillColor: "rgba(151,187,205,0.2)",
                                    strokeColor: "rgba(151,187,205,1)",
                                    pointColor: "rgba(151,187,205,1)",
                                    pointStrokeColor: "#fff",
                                    pointHighlightFill: "#fff",
                                    pointHighlightStroke: "rgba(151,187,205,1)",
                                    data:[]
                                }];
                                <?php foreach($monthlyNewAccounts['all'] as $newAccount){ ?>
                                data.labels.push("<?php echo DateFormatHelper::month($newAccount['m']); ?>");
                                data.datasets[0].data.push(<?php echo $newAccount['c']; ?>);
                                <?php } ?>
                                <?php foreach($monthlyNewAccounts['approved'] as $newAccount){ ?>
                                data.datasets[1].data.push(<?php echo $newAccount['c']; ?>);
                                <?php } ?>
                                data.labels = data.labels.reverse();
                                data.datasets[0].data = data.datasets[0].data.reverse();
                                data.datasets[1].data = data.datasets[1].data.reverse();
                                var ctx = document.getElementById("canvasNewAccounts").getContext("2d");
                                var myLineChart = new Chart(ctx).Line(data, {
                                    animation: false,
                                    scaleShowGridLines : true,
                                    scaleGridLineColor : "rgba(0,0,0,.05)",
                                    scaleGridLineWidth : 1,
                                    bezierCurve : true,
                                    bezierCurveTension : 0.4,
                                    pointDot : true,
                                    pointDotRadius : 4,
                                    pointDotStrokeWidth : 1,
                                    pointHitDetectionRadius : 20,
                                    datasetStroke : true,
                                    datasetStrokeWidth : 2,
                                    datasetFill : true,
                                    legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].lineColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"

                                });
                            </script>
                        </div>
                    </section>
                </div>

            </div>
            <div class="4u">

                <!-- Sidebar -->
                <div id="content">
                    <section class="widget-links">
                        <header>
                            <h2 class="fa fa-2x fa-pie-chart"> Game trends</h2>
                            <p>Amount of gameplays of the last 12 month</p>
                        </header>
                        <div class="grid">
                            <canvas id="canvasOverall" height="240" width="240"></canvas>
                            <script>
                                var data = [];
                                <?php foreach($overallGameplays as $scores){ ?>
                                data.push({
                                    value: <?php echo $scores['cg']; ?>,
                                    color:"#<?php echo $games[$scores['game_id']]['color']; ?>",
                                    highlight: "#<?php echo $games[$scores['game_id']]['color']; ?>",
                                    label: "<?php echo $games[$scores['game_id']]['title']; ?>"
                                });
                                <?php } ?>

                                var ctx = document.getElementById("canvasOverall").getContext("2d");
                                window.myBar = new Chart(ctx).Pie(data, {
                                    segmentShowStroke : true,
                                    segmentStrokeColor : "#fff",
                                    segmentStrokeWidth : 2,
                                    percentageInnerCutout : 0,
                                    animationSteps : 100,
                                    animationEasing : "easeOutBounce",
                                    animateRotate : false,
                                    animateScale : false,
                                    legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>"

                                });
                            </script>
                        </div>
                    </section>

                </div>

            </div>
        </div>
    </div>
</div>


<!-- Features Wrapper -->
<div id="features-wrapper">
    <div class="container">
        <h2 class="fa fa-2x fa-bar-chart"> Monthly gameplays of the last 12 months</h2>
        <div class="row">

            <?php
            if(!$monthlyGameplays){
                echo "Sorry no statistics yet!";
            }
            $i = 0;
            foreach($monthlyGameplays as $game_id => $scores){
                $last = $i%3==2 ? 'last' : '';
            ?>
            <div class="4u">
                <section class="box box-feature <?php echo $last; ?>">
                    <div class="inner">

                        <header>
                            <h2 class="fa fa-2x fa-star"> <?php echo $games[$game_id]['title']; ?></h2>
                        </header>


                        <canvas id="canvas<?php echo $i; ?>" height="240" width="320"></canvas>
                        <script>
                            var barChartData = {
                                labels:[]
                            };
                            barChartData.datasets = [{
                                data : []
                            }];
                            <?php foreach($scores as $score){ ?>
                            barChartData.labels.push("<?php echo DateFormatHelper::month($score[1]); ?>");
                            barChartData.datasets[0].data.push(<?php echo $score[2]; ?>);
                            <?php } ?>
                            barChartData.labels = barChartData.labels.reverse();
                            barChartData.datasets[0].data = barChartData.datasets[0].data.reverse();
                            var ctx = document.getElementById("canvas<?php echo $i; ?>").getContext("2d");
                            window.myBar = new Chart(ctx).Bar(barChartData, {
                                animation: false,
                                responsive : false,
                                scaleBeginAtZero : true,
                                scaleShowGridLines : true,
                                scaleGridLineColor : "rgba(0,0,0,.05)",
                                scaleGridLineWidth : 1,
                                barShowStroke : true,
                                barStrokeWidth : 5,
                                barValueSpacing : 5,
                                barDatasetSpacing : 1
                            });
                        </script>

                    </div>
                </section>
            </div>
            <?php if($i%3==2){ ?>
                </div><div class="row">
            <?php }
                $i++;
                }
            ?>


        </div>
    </div>
</div>

<?php include_once($theme."/html/footer.phtml");?>