<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">
  <div class="gap">
  
   <!-- start -->

	<h2>Buy coins via PayPal!</h2>
	<p>
	Coins represent the internal payment-system on dschini.org. 
	With only 1 coin you may activate a premium game for 30 days.
	</p><p>
	Right now you do not need coins because all games are for free!
	But I am working on a new game, Globetrotter Multiplayer to be exact.
	However, I do not know when this will be finished.
	</p><p>
	Every coin you buy now supports the development and will be added to your account for later use.
	</p><p>
	Please select one of the options below!
	If you dont want to buy coins <a style="text-decoration:underline;" href="/">continue here</a>
	</p>
	<div class="superflow" style="width:100%;">
	
	<?php foreach($products as $product){ ?>
		<div class="box" style="float:left;">
			<div style="margin-right:10px;">
				<div style="width:200px;padding:10px;border:1px dotted #666666;background-color:#eeeeee;">
						<h3 style="padding:2px;">
							<?php echo $product['coins']; ?> coins 
							for
							<?php echo $product['paymentAmount']; ?>
							<?php echo $product['currencyCodeType']; ?>
						</h3>
						<h2 style="padding:2px;">
						→ e.g. <?php echo ($product['coins']*30); ?> days
						</h2>
						<form action="/coins/step2/" method="POST">
						<input type=hidden name=paymentType value='Sale' >
						<p>
						<?php foreach($product as $key=>$value){ ?>
							<input type="hidden" name="<?php echo $key; ?>" value="<?php echo $value; ?>" />
						<?php } ?>
						</p>
						<p>
							<input type="image" name="submit" src="https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif" />
						</p>
					    </form>
				</div>
			</div>
		</div>
	<?php } ?>
	
	</div>


    
   <!-- end -->
  </div>
 </div>
</div>

<?php include_once($theme."/html/payments/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
