<?php include_once($theme."/html/header.phtml");?>
<div id="sub-page">

<div id="content-wrap">
 <div id="content">

  <div class="gap">

   <!-- start -->
	<h2>Cancelled</h2>
	You cancelled the order.
	
	<div class="superflow">
		<div class="box" style="float:left;">
			<div style="margin-right:10px;">
				<div style="width:200px;padding:10px;border:1px dotted #666666;background-color:#eeeeee;">
				
					<p>Have fun playing the free games.</p>
					<p>
					&rarr; <a href="/">Continue here</a>!
					</p>
				</div>
			</div>
		</div>        
	</div>
    
   <!-- end -->
  </div>
 </div>
</div>

<?php include_once($theme."/html/payments/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
