<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">
  <div class="gap">
    <p>
      <h2 style="padding-top:10px;">Die Seite wurde nicht gefunden!</h2>
    </p>
    <div class="entry">
     <p>
       <a href="/">Zur Startseite!</a>
     </p>
    </div>
  </div>
 </div>
</div>

<?php include_once($theme."/html/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>

