<!--
    <p>
    <strong>dschini.com</strong> | .org | .de | .eu</strong>&nbsp; &copy; 2005 - 2014 all rights reserved
    &nbsp; | &nbsp;
    <a href="/about/" style="text-decoration:underline;">about this site</a>
    &nbsp; | &nbsp;
    <a href="/termsconditions/" style="text-decoration:underline;">terms &amp; conditions</a>
    &nbsp; | &nbsp;
	powered by <a href="https://github.com/crafics/mvc-php" style="text-decoration:underline;">crafics/mvc-php</a>
    </p>
-->

<div id="footer-wrapper">
    <footer id="footer" class="container">
        <div class="row">
            <div class="3u">

                <!-- Links -->
                <section class="widget-links">
                    <h2>About</h2>
                    <ul class="style2">
                        <li><a class="fa fa-at solo" href="/about/"> <span>About</span></a></li>
                        <li><a class="fa fa-info solo" href="/termsconditions/"> <span>Terms and conditions</span></a></li>
                        <li><a class="fa fa-area-chart solo" href="/statistics/"> <span>Statistics</span></a></li>
                    </ul>
                </section>

            </div>
            <div class="3u">

                <!-- Links -->
                <section class="widget-links">
                    <h2>Links</h2>
                    <ul class="style2">
                        <li><a href="https://twitter.com/crafics" class="fa fa-twitter solo"> <span>Twitter</span></a></li>
                        <li><a href="http://soundcloud.com/crafics" class="fa fa-soundcloud solo"> <span>Soundcloud</span></a></li>
                        <li><a href="https://www.youtube.com/watch?v=XJ9SCvHjG_I" class="fa fa-youtube solo"> <span>YouTube</span></a></li>
                    </ul>
                </section>

            </div>
            <div class="3u">

                <section class="widget-links">
                    <h2>What others say</h2>
                    <ul class="style2">
                        <li><a class="fa fa-link solo" href="http://jayisgames.com/archives/2009/03/globetrotter_xl.php"> <span>Jay Is Games</span></a></li>
                        <li><a class="fa fa-link solo" href="http://asgamer.com/2009/inspirational-game-globetrotter-xl"> <span>AS Gamer</span></a></li>
                        <li><a class="fa fa-link solo" href="http://www.kongregate.com/games/crafics/globetrotter-xl"> <span>Kongregate</span></a></li>
                        <li><a class="fa fa-link solo" href="http://www.examiner.com/article/globetrotter-xl-international-geographic"> <span>Examiner</span></a></li>
                        <li><a class="fa fa-link solo" href="http://fessicsfavorites.wordpress.com/2009/04/09/globetrotter-xl/"> <span>Fessic</span></a></li>
                    </ul>
                </section>

            </div>
            <div class="3u">

                <!-- Contact -->
                <section class="widget-contact last">
                    <h2>Contact</h2>
                    <!--<ul>
                        <li><a href="#" class="fa fa-facebook solo"><span>Facebook</span></a></li>
                        <li><a href="#" class="fa fa-dribbble solo"><span>Dribbble</span></a></li>
                        <li><a href="#" class="fa fa-google-plus solo"><span>Google+</span></a></li>
                    </ul>-->
                    <p>John Weber<br />
                        Brehmstr.24<br />
                        81543 Munich<br />
                        you@mail.com</p>
                </section>

            </div>
        </div>
        <div class="row">
            <div class="12u">
                <div id="copyright">
                    dschini.com|.org|.de|.eu &copy; 2005-<?php echo date("Y")?> All rights reserved
                </div>
            </div>
        </div>
    </footer>
</div>

</body>
</html>
