<!-- /sub page --> 

<div style="clear:both;"></div>

<div id="footer-all">
  <div id="footer">
    <hr /> 
    <p>
    <strong>dschini.com</strong> | .org | .de | .eu</strong>&nbsp; &copy; 2005 - 2014 all rights reserved
    &nbsp; | &nbsp;
    <a href="/about/" style="text-decoration:underline;">about this site</a>
    &nbsp; | &nbsp;
    <a href="/termsconditions/" style="text-decoration:underline;">terms &amp; conditions</a>
    &nbsp; | &nbsp;
	powered by <a href="https://github.com/crafics/mvc-php" style="text-decoration:underline;">crafics/mvc-php</a>
    </p>
    <br class="clear" /> 
  </div> 
</div>

</body> 
</html> 
