<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="de" >
<head profile="http://gmpg.org/xfn/11"> 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
<meta http-equiv="Pragma" content="no-cache" />
<meta name="author" content="John Weber" />
<meta name="keywords" content="serious, games, spielen, edu, edutainment, educational, e-learning, lernspiele, lernen, spiele, learning, entertainment, education, games"/>
<meta name="description" content="educational games and entertainment" />
<title> 
Dschini -  Educational games and Entertainment!</title> 
<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" /> 
<link rel="shortcut icon" href="/favicon-games.ico" />
<script type="text/javascript" src="/js/mootools.js"></script>
<script type="text/javascript" src="/js/prototype.js"></script> 
<script type="text/javascript" language="JavaScript">
   if(top.frames.length > 0){
     top.location.href=self.location;
   }
</script> 
</head> 
<body> 
<div id="top"> 
  <div id="navr"> 
    <ul class="menu" style="float:left;width:40%;">
    
    
      <?php if( RequestHelper::getInstance()->isController('pageController')
      			&& RequestHelper::getInstance()->isAction('indexAction') ){ ?>
      <li class="current_page_item"><a href="/" title="Games">Games</a></li>
      <?php } else { ?>
      <li class="page_item"><a href="/" title="Games">Games</a></li>
      <?php } ?>
      
      
      <?php if( RequestHelper::getInstance()->isController('pageController')
      			&& RequestHelper::getInstance()->isAction('gameAction') ){ ?>
      &rarr;
      <li class="current_page_item">
      <a href="/game/<?php echo $swf_id ?>/<?php echo $cleanname ?>/" title="<?php echo $game_name; ?>"><?php echo $game_name; ?></a>
      </li>
      <?php } else if(RequestHelper::getInstance()->isController('gameController')) { ?>
      &rarr;
      <li class="page_item">
      <a href="/game/<?php echo $swf_id ?>/<?php echo $cleanname ?>/" title="<?php echo $game_name; ?>"><?php echo $game_name; ?></a>
      </li>
      <?php } else {} ?>
      
      
      <?php if( RequestHelper::getInstance()->isController('gameController') ){ ?>
      <li class="current_page_item">
	  &rarr;
	  <?php if(RequestHelper::getInstance()->isAction('playByGameIdAction')){ ?>
      <a href="/play/<?php echo $swf_id ?>/<?php echo $cleanname ?>/" title="Play <?php echo $game_name; ?>">Play</a>
      <?php } ?>
	  <?php if(RequestHelper::getInstance()->isAction('scoresByGameIdAction')){ ?>
      <a href="/scores/<?php echo $swf_id ?>/0/" title="Play <?php echo $game_name; ?>">Scores</a>
      <?php } ?>
	  <?php if(RequestHelper::getInstance()->isAction('winnersByGameIdAction')){ ?>
      <a href="/winners/<?php echo $swf_id ?>/<?php echo $cleanname ?>/" title="Play <?php echo $game_name; ?>">Winners</a>
      <?php } ?>
      </li>
      <?php } ?>
    </ul>
	<ul class="menu" style="float:right;width:40%;text-align:right;">
		<?php if(isset($_SESSION['user'])) { ?>
 		<li class="page_item">
		<a href="/profile/">Hello <?php echo $_SESSION['user']; ?>
		</li>
		<?php if(isset($_SESSION['approved'])){ ?>
		<li class="page_item"><a href="/logout/">Logout</a></li>
		<?php } ?>
		<?php if(!isset($_SESSION['approved'])){ ?>
		&larr; <a href="/register/" style="color:red;">This name is yours?</a>
		<?php } ?>
		<?php } else { ?>
		<li class="account_panel_item" style="float:right;"><a style="color:black;" href="/login/" title="Login">Click here to login!</a></li>
		<?php } ?>
	</ul>
  </div> 
</div> 
<div id="page"> 
	<div id="pager"> 
	  <div id="header">
	    <a href="/"><img id="logo" src="/img/dschini_medium.png" alt="Dschini - Educational games and Entertainment" /></a>
	  </div> 
	</div> 
	<hr />
	<div style="border-top:2px dotted #ccc;"></div> 
