<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">


<div style="padding-bottom:30px;">
<h2>Thanks!</h2>
</div>

<div class="gap">
<p>
<a href="http://roland-hummer.at" target="_blank"><img src="/img/logo-roland-hummer.gif" /></a>
<p>Roland Hummer a freethinker, lateral thinker and visionary. He offers you new perspectives for spontaneous ideas, creative designs, attractive concepts and visualisations in any sector in an interplay between custom, tolerance and holistic creativity</p>
<a href="http://roland-hummer.at" target="_blank" style="text-decoration:underline;">Visit Roland Hummer here</a>
</p>
</div>

<div style="padding-bottom:50px;">
</div>

<div class="gap">
<h2>Donate!</h2>

<p>
Developing games is my passion! I already spent several month developing the games on dschini.org. Time that is actually not payed. Not to mention the money I spent for the server costs.
<br/>
If you're playing the games on dschini.org you probably noticed that everything is for free. There're no tricks envolved ( like In-game items, trial versions, ... ) to make money with the games. I am just an individual having fun developing games. Nothing more and nothing less.
<br/>
Now you might ask: "What about the Ads on this page?" ... Well, with about 30$ a month they do not even pay the server costs (ca 60$)! 
<br/>
I do not own a business plan for this site and have no interest to change that in the future.
</p>
<p>
Now I ask for your help. If you enjoy playing the games on this site and think you can afford some money, please help me and donate!
</p>

<div style="padding:10px;">
<p>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_donations">
<input type="hidden" name="business" value="you@mail.com">
<input type="hidden" name="lc" value="US">
<input type="hidden" name="item_name" value="John">
<input type="hidden" name="currency_code" value="EUR">
<input type="hidden" name="bn" value="PP-DonationsBF:btn_donateCC_LG.gif:NonHostedGuest">
<input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
</div>

<p>
I will list everyone who donated here on this page with a link to your site and some text (statement)! After you donated, please drop me a note (you@mail.com) with a link to your site and optional some text that you want to get displayed here. Thank you!
</p>

  </div>
 </div>
</div>

<?php include_once($theme."/html/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
