<?php include_once($theme."/html/header.phtml");?>

<style type="text/css">
table.padded-table td { padding:5px; }
</style>

<div id="sub-page">
	<div id="content-wrap"> 
		<div id="content"> 
			<div class="gap"> 
<div style="width:90%;padding:5px;">
<p>
<script type="text/javascript"><!--
google_ad_client = "pub-2152695889021074";
/* 728x15, Erstellt 06.02.09 */
google_ad_slot = "3564810151";
google_ad_width = 728;
google_ad_height = 15;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</p>                                </div>
				<div class="post lastlast"> 
					<a href="/play/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/" rel="bookmark" title="Play: <?php echo $game['title'] ?>">
					<div class="tumbr" style="z-index:2;margin-left: 10px;float:right; width: 295px; height: 190px; background: url(<?php echo $game['img'] ?>) 0 0 no-repeat; content: ">
					</div></a>
					<div class="superlast clearfix"> 
						<h2>
							<a href="/game/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/" rel="bookmark" title="<?php echo $game['title'] ?>"><?php echo $game['title'] ?></a>
						</h2>
						<div class="entry">
							<p>
							<?php echo $game['body'] ?>
							</p>
							<p>
							More information about this game: <a target="_blank" href="<?php echo $game['more'] ?>">See this post!</a>
							</p>
							<p>
							&rarr; Coins: <?php echo $game['coins']==0 ? 'Free!' : $game['coins']; ?>
							<br/>
							&rarr; Gameplays this month: <?php echo $amountOfTotalGameplaysByGameId; ?>
							<br/>
							&rarr; Gameplays today: <?php echo $currentGameplaysByGameId; ?>
							</p>
						</div>
					</div>
					<div style="clear:both;"></div>
				</div>
				<div class="superflow">
					<!--  current leadership -->
					<div class="box" style="float:left;width:33%;">
						<div style="margin:10px;">
							<h3 style="padding:2px;">Current Leadership</h3>
							<div style="height:220px;border:1px dotted #666666;background-color:#eeeeee;">
								<table style="width:100%;height:100%;" class="padded-table">
									<?php if($currentLeadershipByGameId){ ?>
									<tr>
										<td style="width:10%;border-bottom:1px dotted #999;">&nbsp;</td>
										<td style="width:45%;border-bottom:1px dotted #999;">Player</td>
										<td style="width:35%;border-bottom:1px dotted #999;">Score</td>
										<td style="width:10%;border-bottom:1px dotted #999;">Level</td>
									</tr>
									<?php $i=1; foreach($currentLeadershipByGameId as $leader){ ?>
									<tr>
										<td><?php echo $i++; ?></td>
										<td><a href="/player/<?php echo $leader['user']; ?>/"><?php echo $leader['user']; ?></a></td>
										<td><?php echo $leader['score']; ?></td>
										<td>
										<?php 
										if(($game_id==7 || $game_id==6) && $leader['level']>=11){
											echo 'Win'; 
										} else{
											echo $leader['level']; 
										}
										?>
									</tr>
									<?php } ?>
									<tr>
										<td colspan="4">
											<!--&rarr; <a href="/scores/<?php echo $game_id; ?>/0/" style="padding-top:5px;text-decoration:underline;">See all</a>-->
										</td>
									</tr>
									<?php } else { ?>
									<tr>
										<td valign="top"><p>No Leadership yet!</p></td>
									</tr>
									<?php } ?>
								</table>
							</div>
						</div>
					</div>
					<!--  alltime stars -->
					<div class="box" style="float:left;width:33%;">
						<div style="margin:10px;">
							<h3 style="padding:2px;">Alltime Heros</h3>
							<div style="height:220px;border:1px dotted #666666;background-color:#eeeeee;">
								<table style="width:100%;height:100%;" class="padded-table">
									<?php if($allTimeStarsByGameId){ ?>
									<tr>
										<td style="width:10%;border-bottom:1px dotted #999;">&nbsp;</td>
										<td style="width:45%;border-bottom:1px dotted #999;">Player</td>
										<td style="width:35%;border-bottom:1px dotted #999;">Score</td>
										<td style="width:10%;border-bottom:1px dotted #999;">Level</td>
									</tr>
									<?php $i=1; foreach($allTimeStarsByGameId as $star){ ?>
									<tr>
										<td><?php echo $i++; ?></td>
										<td><a href="/player/<?php echo $star['user']; ?>/"><?php echo $star['user']; ?></a></td>
										<td><?php echo $star['score']; ?></td>
										<td>
										<?php 
										if(($game_id==7 || $game_id==6) && $star['level']>=11){
											echo 'Win'; 
										} else{
											echo $star['level']; 
										}
										?>
										</td>
									</tr>
									<?php } ?>
									<tr>
										<td colspan="4">
											<!-- &rarr; <a href="/winners/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/" style="padding-top:5px;text-decoration:underline;">See all</a> -->
										</td>
									</tr>
									<?php } else { ?>
									<tr>
										<td valign="top"><p>No heros yet!</p></td>
									</tr>
									<?php } ?>
								</table>
							</div>
						</div>
					</div>
					<!--  infobox -->
					<div class="box" style="float:left;width:33%;">
						<div style="margin:10px;">
							<h3 style="padding:2px;">Ads</h3>
							<div style="height:220px;border:1px dotted #666666;background-color:#eeeeee;">
								<table style="width:100%;height:100%;" class="padded-table">
									<tr>
										<td valign="top">
<p>
<script type="text/javascript"><!--
google_ad_client = "pub-2152695889021074";
/* 200x200, Erstellt 08.02.09 */
google_ad_slot = "8669858167";
google_ad_width = 200;
google_ad_height = 200;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</p>
										<?php if($game['coins']==0){ ?>
										<!--<p>
											&rarr; <a href="/play/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/">Play now!</a>
										</p>-->
										<?php } else if($game['coins']>=0) { ?>
											<?php if(!isset($_SESSION['accountId'])){ ?>
											<p>
												This game is not for free and requires an account!
												<br/>
												&rarr; <a href="/register/">Sign in!</a>
												<br/>
												&rarr; <a href="/login/?next=/game/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/">Login!</a>
											</p>
											<?php } else { ?>
												<?php if($accountProduct){ ?>
												<p>
													This game expires on:
													<br/>
													<?php echo DateFormatHelper::standard($accountProduct->expires); ?>
													<br/>
													&rarr; <a href="/play/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/">Play now!</a>
												</p>
												<?php } else { ?>
													<?php if($amountCoins<$game['coins']){ ?>
													<p>
														You require <b><?php echo $game['coins']>1 ? $game['coins'].' coins ' : $game['coins']. ' coin'; ?></b> to activate this game.
														<br/>
														&rarr; <a href="/coins/">Buy coins!</a>
													</p>
													<?php } else { ?>
													<p>
														You require <b><?php echo $game['coins']>1 ? $game['coins'].' coins ' : $game['coins']. ' coin'; ?></b> to activate this game for 30 days.
														<br/>
														&rarr; <a href="/buy/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/?next=/play/<?php echo $game_id; ?>/<?php echo $game['cleanname'] ?>/">Activate this game!</a>
													</p>
													<?php } ?>
												<?php } ?>
											<?php } ?>
										<?php } ?>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- /gap --> 
		</div> <!-- /content --> 
	</div> <!-- /content-wrap -->


<?php include_once($theme."/html/pages/sidebar.phtml");?>

<br class="clear" />
</div>
</div>
<?php include_once($theme."/html/footer.phtml");?>
