<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">
  <div class="gap">
  
<p>
<img src="/img/globetrottermobile.png" />
</p>
<p>
<br/>
<h2>Globetrotter 1.2 - Mobile</h2>
</p>
<p>
Globetrotter for Android and iPhone/iPad has been released. The versions are different and have been redesigned from scratch. The new features like zooming and highscores make a compelling gameplay.
</p>
<p>
<b>Play Globetrotter and improve your geographic skills.</b>
</p>
Globetrotter is a fun, fast-paced world geography game. You are presented with a map of the entire world, and asked to locate a number of cities. If you can locate them correctly enough, you will proceed to the next level. 
</p>
<p>
Bonus multipliers are given for guessing within a few hundred kilometers, and an even greater multiplier for guessing within around kilometers.
</p>
<p style="color:blue;">
<b>There're lots of things to improve. So expect regular updates.</b>
</p>
<p>
<b>Please provide feedback!</b>
</p>
<p>
Send an email to you@mail.com if you have ideas on how to improve the mobile version of Globetrotter!
</p>

  </div>
 </div>
</div>
<?php include_once($theme."/html/pages/globetrottermobilesb.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
