<div id="sidebar">
	<div class="side1">
		
		<div class="gapy" id="donate"> 
			<h2 style="border-top:none;color:#999;font-weight:normal;">iPhone / iPad</h2>
			<img src="/img/globetrotteriphone48.png" style="float:left;margin-right:5px;">
			<a href="http://itunes.apple.com/us/app/globetrotter/id418882144?mt=8&ls=1" target="_blank" style="text-decoration:underline;"><b>Globetrotter 1.2 - XL</b></a>
			<br/>
			The XL version runs on iPad and iPhone.
			<a href="http://itunes.apple.com/us/app/globetrotter/id418882144?mt=8&uo=4" target="itunes_store" style="text-decoration:underline;">Get it here!</a>
 
		</div>

		<br style="clear:left;" />

                <div class="gapy" id="donate">
                        <h2 style="border-top:none;color:#999;font-weight:normal;">Android</h2>
			<img src="/img/globetrotterlightandroid48.png" style="float:left;margin-right:5px;">
                        <a href="https://market.android.com/details?id=air.globetrotter" target="_blank" style="text-decoration:underline;"><b>Globetrotter 1.2 - Lite</b></a>
			<br/>
			The free Lite version is fully playable but limited to 5 levels and lesser cities.
			<a href="https://market.android.com/details?id=air.globetrotter" target="_blank" style="text-decoration:underline;">Get it here!</a>

                </div>


                <div class="gapy" id="donate">

			<img src="/img/globetrotterxlandroid48.png" style="float:left;margin-right:5px;">
                        <a href="https://market.android.com/details?id=air.globetrotterxl" target="_blank" style="text-decoration:underline;"><b>Globetrotter 1.2 - XL</b></a>
			<br/>
                        The XL version features 10 levels, hundreds of cities and appealing sound.
			<a href="https://market.android.com/details?id=air.globetrotterxl" target="_blank" style="text-decoration:underline;">Get it here!</a>
                </div>
		
	</div>
</div>
 
