<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">
  <div class="gap">

<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
        codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0"
        width="768"
        height="640"
        id="game"
        align="middle"> 
<param name="movie" value="http://games.mochiads.com/c/g/molecules_v793134/Molecules.swf" /> 
<param name="allowScriptAccess" value="always" /> 
<param name="allowFullScreen" value="true" /> 
<param name="menu" value="false" /> 
<param name="quality" value="high" /><param name="bgcolor" value="#ffffff" /> 
        <embed src="http://games.mochiads.com/c/g/molecules_v793134/Molecules.swf"
                        quality="high"
                        menu="false"
                        bgcolor="#ffffff"
                        width="768"
                        height="640"
                        allowFullScreen="true"
                        name="game"
                        align="middle"
                        allowScriptAccess="always"
                        type="application/x-shockwave-flash"
                        pluginspage="http://www.macromedia.com/go/getflashplayer" /> 
</object> 

  </div>
 </div>
</div>
<?php include_once($theme."/html/pages/globetrottermobilesb.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
