<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">
  <div class="gap">
  
<h2>TERMS AND CONDITIONS</h2>

<p>
By viewing or accessing games.dschini.org you expressly agree to the following Terms and 
Conditions detailed below.
</p>
<p>
Your use of the games.dschini.org website and/or use of the games, 
software, applications, products or services signifies your acceptance of these Terms and 
Conditions and constitutes a legally binding acceptance of this agreement. 
If you do not agree to these conditions you are not allowed to access or use the games on games.dschini.org.
Software, applications, products or services. games.dschini.org 
reserves the right to modify, alter and update the content of these Terms and Conditions 
at anytime. The current terms and conditions will be posted 
here: http://games.dschini.org/termsconditions/
</p>
<p>
Although games.dschini.org attempts to ensure that all information contained on this website 
is error-free, we accept no liability for omissions, and reserve the right to change or 
alter the content of the site at anytime. games.dschini.org does not make any warranty that 
the website is free from infection from viruses; nor does any provider of content to the 
site or their respective agents make any warranty as to the results to be obtained from use of the site.
</p>
<p>
UNDER NO CIRCUMSTANCES INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL GAMES.DSCHINI.ORG BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF OR INABILITY TO 
USE THE GAMES.DSCHINI.ORG WEB SITE, SOFTWARE AND/OR SERVICES, EVEN IF SUCH PARTY HAS BEEN 
ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
</p>
<p>
YOU AGREE TO ASSUME ALL RISK RELATED TO YOUR USE OF GAMES.DSCHINI.ORG AND SERVICES, INLCUDING 
BUT NOT LIMITED TO, THE RISK OF COMMUNICATIONS WITH OTHER PEOPLE OR DAMAGE TO YOUR COMPUTER.
</p>

<p>
<b>Unsubscribe the Newsletter</b>
</p>
<p>
You may alter your settings on your profile page which is work in progress. 
If that does not work send an email to you@mail.com with the email address
you would like removed and ‘REMOVE’ in the subject line.
</p>

<p>
<b>Age restrictions</b>
</p>
<p>
We do not target users under 13 of age. 
There may be certain access restrictions placed on any under 13 year old users.
You agree that if you assist users under 13 years old to access the games.dschini.org, 
with your computer, internet enabled device, internet connection and/or facilities (whether owned, leased or borrowed) 
that you will assume full liability for any consequences and that UNDER NO CIRCUMSTANCES INCLUDING, 
BUT NOT LIMITED TO, NEGLIGENCE NEITHER GAMES.DSCHINI.ORG, ANY THIRD PARTY CONTENT PROVIDER NOR THEIR 
RESPECTIVE AGENTS SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES 
ARISING OUT OF THE USE OF OR INABILITY TO USE THE SITE BY USERS UNDER 13 YEARS OF AGE, EVEN IF SUCH PARTY 
HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
</p>

<p>
<b>Links</b>
</p>
<p>
games.dschini.org accepts no responsibility for the links to or from its website and the inclusion of these links 
does not mean that games.dschini.org endorses the material or content of these sites.
</p>

<p>
<b>Advertisments</b>
</p>
<p>
games.dschini.org accepts no responsibility for any third party advertisements that may appear on games.dschini.org.
</p>

<p>
<b>Online Purchases</b>
</p>
<p>
We are not liable for errors in pricing at our online products. If a product was not priced properly as determined by 
games.dschini.org, we have the right to correct the price on any previously placed orders and re-price the product 
or refund any purchases on the product.
Your debit/credit card account will be billed as ‘DSCHINI’.
A payment is authorized immediately and collected in 3 working days.
</p>
<p>
<b>User Rules</b>
</p>
<p>
Users may be banned or accounts suspended or terminated on the entire games.dschini.org website or any game 
available on games.dschini.org if users use inappropriate langauge or inappropriate behavior as determined 
by games.dschini.org. Inappropriate language and/or inappropriate behavior is not allowed on games.dschini.org. 
games.dschini.org is not responsible for user content, postings, chat, and/or communications. 
Users are responsible for their own actions.
</p>
<p>
<b>You agree not to do any of the following:</b>
</p>
<p>
→ Post, distribute, or otherwise make available or transmit any data, text, message, or computer file that we deem to 
be: (a) defamatory, abusive, harassing, insulting, threatening, or that could be deemed to be stalking; (b) bigoted, 
hateful, or racially offensive; (c) vulgar, obscene, or sexually explicit (language or images); or that (d) encourages 
or advocates illegal activity or the discussion of illegal activities with the intent to commit them;
</p>
<p>
→ Post, distribute, or otherwise make available or transmit any data, text, message, computer file, or other material 
that infringes and/or violates any right of a third party or any domestic or international law, rule, or regulation, 
including but not limited to: (a) copyright, patent, trademark, or other proprietary rights; (b) right of privacy (specifically, 
you must not distribute another person's personal information of any kind without their express permission) or 
publicity; (c) any confidentiality obligation;
</p>
<p>
→ Advertise or sell any products, services or otherwise (whether or not for profit), or solicit others or use any Forum 
for commercial purposes of any kind,
</p>
<p>
→ Post, distribute, or otherwise make available or transmit any software or other computer files that contain a virus or 
other harmful component;
</p>
<p>
→ Impersonate any person or entity or misrepresent your identity or affiliation with any person or entity;
</p>
<p>
→ Engage in antisocial, disruptive, or destructive acts, including "flaming," "spamming," "flooding," "trolling," and "griefing" as 
those terms are commonly understood and used on the Internet;
</p>
<p>
→ Delete any legal notices, disclaimers, or proprietary notices such as copyright or trademark symbols, or modify any logos that 
you do not own or have express permission to modify;
</p>
<p>
→ Post, distribute, or otherwise make available or transmit material or make statements that do not generally pertain to the 
designated topic or theme of any Forum.
</p>
<p>
We reserve the right to remove any material, and if we deem appropriate, to turn over to law enforcement officials, any material, 
including message, e-mail, or posting, that is in violation of these Rules. We also reserve the right to remove messages, e-mails, 
or postings that do not pertain to the designated topic or theme of the service as determined by games.dschini.org.
</p>
<p>
We also reserve the right to comply with any order or otherwise cooperate with law enforcement officials regarding the 
identification of any user alleged to be using games.dschini.org in violation of the law.
</p>
<p>
<b>PRIVACY POLICY</b>
</p>
<p>
games.dschini.org is committed to providing an entertaining, fun and educational service. 
games.dschini.org respects the privacy concerns of visitors. games.dschini.org does not target its website or 
services to under 13 year olds, but does take measures 
to help protect those that happen to be under 13. We take measures to help children protect their privacy while 
online. For example, we do not ask children to disclose more personal information than is necessary for them to 
participate in a particular activity.
</p>
<p>
<b>Information we collect</b>
</p>
<p>
We may log IP addresses and/or drop cookies to prevent abuse of our website and/or to enhance services. 
</p>
<p>
<b>How we use the information</b>
</p>
<p>
We do not retain any personal information beyond the time it is needed. 
We may use information to ensure that users are compliance with our terms. 
games.dschini.org may disclose information in special cases when we have reason to believe that disclosing this 
information is necessary to identify, contact or bring legal action against someone who may be 
causing injury to or interference with games.dschini.org property, visitors, or anyone else 
that could be harmed by such activities.
</p>
<p>
We may sometimes use non-personally identifiable information that we collect to improve the design and content 
of our site, to personalize our visitors' experience or to offer products, programs, and services. 
We may also use this information in the aggregate to analyze site usage, as well as to offer products, programs, or services.
</p>
<p>
<b>Security</b>
</p>
<p>We have implemented appropriate physical, electronic, and managerial procedures to safeguard and help prevent 
unauthorized access, maintain data security, and correctly use the information we collect online.
</p>
<p>
<b>Parental Review</b>
</p>
<p>
Parents, if you would like to review your child's personal information, ask to have it deleted, and refuse to 
allow any further collection or use of the child's information then please send an email to you@mail.com.
Please be sure to include your email address and a telephone number where we can reach you. 
To protect your child's privacy and security, we will take reasonable steps to help verify your identity before 
granting you access to the personal information that we collect and maintain about your child.
</p>
<p>
<b>Changes to this Privacy Policy</b>
</p>
<p>
This Privacy Policy is part of the games.dschini.org main Terms and Conditions which you agree to by accessing 
our webstie. You agree that games.dschini.org may change this Privacy Policy and the main Terms and Conditions at any time. 
</p>
<p>
<b>Internet Safety</b>
</p>
<p>
We recommend that Parents take time to communicate and educate their children about Internet Safety. 
</p>
<p>
<b>Acceptable Use Policy</b>
</p>
<p>
We have no tolerance for any misuse of our website for any immoral, illegal or other activity deemed to be 
inappropriate by games.dschini.org. 
We hold any user of our website responsible for any misappropriate behavior which includes any attempt to use 
our system for spamming or any other type of abuse. 
If we get a complaint we can investigate and if necessary track down the person or persons responsible the 
activity to take any necessary actions such as prosecution.
</p>
<p>
<b>GAME LICENSE AGREEMENT</b>
</p>
<p>
Use of the Software is contingent on your agreement to the following terms:
</p>
<p>
Our Software may not be used on any other sites except we created a seperate contract for that.
</p>
<p>
<b>DISCLAIMER OF WARRANTY</b>
</p>
<p>
THE SOFTWARE IS PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND. 
FURTHER DISCLAIMS ALL WARRANTIES, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF 
MERCHANT ABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND ON INFRINGEMENT. 
THE ENTIRE RISK ARISING OUT OF THE USE OR PERFORMANCE OF THE PRODUCT AND 
DOCUMENTATION REMAINS WITH THE RECIPIENT. 
TO THE MAXIMUM EXTENT PERMITTED BY 
APPLICABLE LAW, IN NO EVENT SHALL GAMES.DSCHINI.ORG BE LIABLE FOR ANY CONSEQUENTIAL, INCIDENTAL, 
DIRECT, INDIRECT, SPECIAL, PUNITIVE, OR OTHER DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, 
DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR 
OTHER PECUNIARY LOSS) ARISING OUT OF THIS AGREEMENT OR THE USE OF OR INABILITY TO USE THE PRODUCT, 
EVEN IF GAMES.DSCHINI.ORG HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. 
THIS SOFTWARE AND THE ACCOMPANYING FILES ARE SOLD "AS IS" AND WITHOUT WARRANTIES AS TO PERFORMANCE 
OR MERCHANT ABILITY OR ANY OTHER WARRANTIES WHETHER EXPRESSED OR IMPLIED. Because of the various 
hardware and software environments into which the Software may be put, NO WARRANTY OF FITNESS FOR 
A PARTICULAR PURPOSE IS OFFERED. The user must assume the entire risk of using the Software. 
ANY LIABILITY OF THE SELLER WILL BE LIMITED EXCLUSIVELY TO PRODUCT REPLACEMENT OR REFUND OF PURCHASE PRICE.
</p>
<p>
<b>SCOPE OF GRANT</b>
</p>
<p>
You may not reverse engineer, decompile, disassemble or modify our Software in any way. 
games.dschini.org shall retain title and all ownership rights to the Software.
</p>
<p>
<b>COPYRIGHT</b>
</p>
<p>
This SOFTWARE is protected by copyright laws and international copyright treaties, as well as other intellectual property laws and treaties.
</p>
<p>
<b>MAINTENANCE</b>
</p>
<p>
We are not obligated to provide maintenance or updates for the SOFTWARE. 
However, any maintenance or updates provided by games.dschini.org shall be covered by this Agreement.
</p>
<p>
<b>DISTRIBUTION</b>
</p>
<p>
You are not licensed to make any copies of this SOFTWARE.
</p>
<p>
<b>CUSTOM LICENSE AGREEMENTS</b>
</p>
<p>
If you wish to use the SOFTWARE for any other purpose such as CD distribution you may apply for a custom licensing 
agreement at you@mail.com
</p>
<p>
<b>Copyright</b>
</p>
<p>
If you believe that your copyrightable work is being displayed on this site and is violating copyright 
regulations - please advise us immediately at you@mail.com and we will remove it.
</p>
  </div>
 </div>
</div>

<?php include_once($theme."/html/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>