<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">
  <div class="gap">

   <!-- start -->
<div class="formin">
<form action="" method="post" id="form"> 

  <p>
    <h2 style="padding-top:10px;border-bottom:1px dotted #ccc;">Logout</h2>
  </p>
  <p>
  	You logged out!
  	<br/>
  	<script type="text/javascript">
  	function next(){
	  	window.location.href = '/login/';
  	}
  	window.setTimeout("next()", 3000);
  	</script>
  </p>
</div> 
   <!-- end -->

  </div>
 </div>
</div>

<?php include_once($theme."/html/accounts/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
