<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">
  <div class="gap">

   <!-- start -->
<div class="formin"> 
<form action="" method="post" id="form"> 

  <?php if(count($error)>0){ ?>
  <p>
    <h1 style="color:red;">Ooops!</h1>
    <?php if(isset($error["account"])){ ?>
	    <?php 
	    switch($error["account"]){
	    	case 'could_not_find': 
	    ?>
	    <h3 style="color:red;">Could not find your email address!</h3>
	    <?php 
	    	break; 
	    }
	    ?>
	<?php } else { ?>
    <h3 style="color:red;">Something is wrong!</h3>
	<?php } ?>
  </p>
  <?php } ?>
  <p>
    <h2 style="padding-top:10px;border-bottom:1px dotted #ccc;">Lost password?</h2>
  </p>
  <p>
  	Please tell us your email address!
  </p>
  <p>
    <label for="email"><small>Email:</small> <b style="position:relative;z-index:2;top:20px;color:red;font-size:48px;">*</b></label>
  </p>
  <p>
    <input type="text" name="email" id="email" value="<?php echo $email; ?>" maxlength="100" size="40" style="<?php echo isset($error['email'])?'border:1px solid red':''; ?>" /> 
  </p>
 <p>
    <!-- nr1 & nr2-->
    <label for="name"><small>Please answer the following question: </small> <b style="position:relative;z-index:2;top:20px;color:red;font-size:48px;">*</b></label>
  </p>
  <p>
    <b style="font-size:16px"><?php echo $nr1; ?> + <?php echo $nr2; ?> = </b>
    <input type="hidden" name="nr1" id="nr1" value="<?php echo $nr1; ?>" />
    <input type="hidden" name="nr2" id="nr2" value="<?php echo $nr2; ?>" />
    <input type="text" name="total" id="total" value="" size="4" maxlength="3" style="<?php echo isset($error['total'])?'border:1px solid red':''; ?>" /> 
  </p>
  <!-- Submit -->
  <p style="padding-top:10px;"> 
   <input name="next" type="submit" id="submit" value="GO &rarr;" /> 
  </p> 
  </form> 
</div> 
   <!-- end -->

  </div>
 </div>
</div>

<?php include_once($theme."/html/accounts/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
