<?php include_once($theme."/html/header.phtml");?>

<div id="sub-page">

<div id="content-wrap">
 <div id="content">
  <div class="gap">

   <!-- start -->
<div class="formin"> 

  <p>
    <h2 style="padding-top:10px;border-bottom:1px dotted #ccc;">OK</h2>
  </p>
  <p>
  	The login data has been sent to you!
  </p>
</div> 
   <!-- end -->

  </div>
 </div>
</div>

<?php include_once($theme."/html/accounts/sidebar.phtml");?>

<br class="clear" />
</div>
</div>

<?php include_once($theme."/html/footer.phtml");?>
