<?php include_once($theme."/html/header.phtml");?>

<!-- Main Wrapper -->
<div id="main-wrapper">
    <div class="container">
        <div class="row">


            <div class="12u skel-cell-important">

                <!-- Content -->
                <div id="content">
                    <section class="last">
                        <h2 class="fa fa-2x">About</h2>
                        <p>Inhaltlich Verantwortlicher gemäß §10 Absatz 3 MDStV:</p>
                        <p>John Weber<br>
                            Brehmstr. 24<br>
                            81543 München<br/>
                            you@mail.com<br>
                        </p>
                        <p>Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links.</p>
                        <p>Für den Inhalt der verlinkten Seiten sind ausschliesslich deren Betreiber verantwortlich.</p>
                    </section>
                </div>

            </div>
        </div>
    </div>
</div>


<?php include_once($theme."/html/footer.phtml");?>
