<?php include_once($theme."/html/header.phtml");?>

<!-- Main Wrapper -->
<div id="main-wrapper">
    <div class="container">
        <div class="row">


            <div class="12u skel-cell-important">

                <!-- Content -->
                <div id="content">
                    <section class="last">
                        <h2>Cancelled</h2>
                        You cancelled the order.

                        <div class="superflow">
                            <div class="box" style="float:left;">
                                <div style="margin-right:10px;">
                                    <div style="width:200px;padding:10px;border:1px dotted #666666;background-color:#eeeeee;">

                                        <p>Have fun playing the free games.</p>
                                        <p>
                                            &rarr; <a href="/">Continue here</a>!
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>

            </div>
        </div>
    </div>
</div>


<?php include_once($theme."/html/footer.phtml");?>
